from character import Character


def initializeCharacters():
    characterList = []
    characterList.append(Character("Traveler", "Dendro", "Sub DPS"))
    characterList.append(Character("Jean", "Anemo", "Healer", "Buffer"))
    characterList.append(Character("Noelle", "Geo", "DPS", "Healer"))
    characterList.append(Character("Sucrose", "Anemo", "Buffer"))
    characterList.append(Character("Fischl", "Electro", "Sub DPS"))
    characterList.append(Character("Mona", "Hydro", "Buffer"))
    characterList.append(Character("Kaeya", "Cryo", "Sub DPS"))
    characterList.append(Character("Diluc", "Pyro", "DPS"))
    characterList.append(Character("Razor", "Electro", "DPS"))
    characterList.append(Character("Bennett", "Pyro", "Healer", "Buffer"))
    characterList.append(Character("Beidou", "Electro", "Sub DPS"))
    characterList.append(Character("Keqing", "Electro", "DPS"))
    characterList.append(Character("Xiangling", "Pyro", "Sub DPS"))
    characterList.append(Character("Chongyun", "Cryo", "Sub DPS"))
    characterList.append(Character("Xingqui", "Hydro", "Sub DPS"))
    characterList.append(Character("Venti", "Anemo", "Sub DPS", "Buffer"))
    characterList.append(Character("Klee", "Pyro", "DPS"))
    characterList.append(Character("Diona", "Cryo", "Healer", "Shielder"))
    characterList.append(Character("Zhongli", "Geo", "Shielder"))
    characterList.append(Character("Albedo", "Geo", "Sub DPS"))
    characterList.append(Character("Ganyu", "Cryo", "DPS", "Sub DPS"))
    characterList.append(Character("Hu Tao", "Pyro", "DPS"))
    characterList.append(Character("Rosaria", "Cryo", "Sub DPS"))
    characterList.append(Character("Kazuha", "Anemo", "Buffer"))
    characterList.append(Character("Raiden", "Electro", "DPS", "Sub DPS"))
    characterList.append(Character("Sara", "Electro", "Buffer"))
    characterList.append(Character("Kokomi", "Hydro", "Healer", "DPS"))
    characterList.append(Character("Thoma", "Pyro", "Shielder", "Sub DPS"))
    characterList.append(Character("Gorou", "Geo", "Buffer"))
    characterList.append(Character("Shenhe", "Cryo", "Sub DPS"))
    characterList.append(Character("Yae Miko", "Electro", "Sub DPS"))
    characterList.append(Character("Yelan", "Hydro", "Sub DPS", "Buffer"))
    characterList.append(Character("Kuki", "Electro", "Healer", "Sub DPS"))
    characterList.append(Character("Heizou", "Anemo", "DPS", "Sub DPS"))
    characterList.append(Character("Tighnari", "Dendro", "DPS", "Sub DPS"))
    characterList.append(Character("Candace", "Hydro", "Buffer", "Sub DPS"))
    characterList.append(Character("Nilou", "Hydro", "Buffer", "Sub DPS"))
    characterList.append(Character("Nahida", "Dendro", "Buffer", "Sub DPS"))
    characterList.append(Character("Layla", "Cryo", "Shielder"))
    characterList.append(Character("Wanderer", "Anemo", "DPS"))
    characterList.append(Character("Faruzan", "Anemo", "Buffer"))
    characterList.append(Character("Yao Yao", "Dendro", "Healer"))
    characterList.append(Character("Neuvillette", "Hydro", "DPS"))
    characterList.append(Character("Furina", "Hydro", "Buffer", "Sub DPS"))
    characterList.append(Character("Charlotte", "Cryo", "Healer"))
    characterList.append(Character("Navia", "Geo", "DPS", "Sub DPS"))
    characterList.append(Character("Dori", "Electro", "Healer", "DPS"))
    characterList.append(Character("Freminet", "Cryo", "DPS", ))
    characterList.append(Character("Childe", "Hydro", "DPS"))
    characterList.append(Character("Gaming", "Pyro", "DPS"))
    characterList.append(Character("Arlecchino", "Pyro", "DPS"))
    characterList.append(Character("Chevreuse", "Pyro", "Buffer"))
    characterList.append(Character("Chlorinde", "Electro", "DPS"))
    characterList.append(Character("Kirara", "Dendro", "Shielder"))
    characterList.append(Character("Kinich", "Dendro", "DPS"))
    characterList.append(Character("Dehya", "Pyro", "Sub DPS"))
    characterList.append(Character("Mika", "Cryo", "Healer"))
    characterList.append(Character("Barbara", "Hydro", "Healer"))





    return characterList
